package com.pichincha.cuentasbancarias.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import lombok.*;

import java.math.BigDecimal;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@DynamoDBTable(tableName = "pichincha_CuentasBancarias")
public class CuentaBancaria {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id_cuentaBancaria;
    @DynamoDBAttribute
    private String numeroCuenta;
    @DynamoDBAttribute
    private String tipoCuenta;
    @DynamoDBAttribute
    private String nombreTitular;
    @DynamoDBAttribute
    private BigDecimal saldo;


}
